version: '2'  
services:  
  nginx:
    restart: always
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:8000"
    volumes:
      - ./src:/src
      - ./config/nginx:/etc/nginx/conf.d
      - ../static:/static
    depends_on:
      - backend
  backend:
    restart: always
    build:
      context: .
      dockerfile: ./config/backend/Dockerfile
    container_name: backend
    environment:
      - DJANGO_SETTINGS_MODULE=sesamo.settings.production
    entrypoint:
      - /entrypoint.sh
    depends_on:
      - db
    volumes:
      - ./src:/src
      - ../static:/static
    expose:
      - "8000"
  db:
    image: postgres:latest
    volumes:
        - ../postgres-data:/var/lib/postgresql/data